apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.1.9:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: K2F1eGIzR3JQb3lrV2pDTUNGdzBWL0ZocjJXTCsycVhBamNRL0tUMjlBQT0K

